### ISSUE TITLE
fgets and gets_s have swapped file names

### ISSUE THREAD

**Issue by mlfaw** [ForwardCom/libraries#1]
https://github.com/ForwardCom/libraries/blob/16ccf5f0c0ebb2eb087125927c60ce4d9bc22a09/fgets.as
https://github.com/ForwardCom/libraries/blob/16ccf5f0c0ebb2eb087125927c60ce4d9bc22a09/gets_s.as

**Comment by AgnerF** [comment]
Thanks. Sorry I didn't notice.
